# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
      - id: check-added-large-files  # prevents giant files from being committed.
        args: ['--maxkb=4096']
      - id: check-ast  # simply checks whether the files parse as valid python.
      - id: check-symlinks  # checks for symlinks which do not point to anything.
      - id: check-toml  # checks toml files for parseable syntax.
      - id: check-yaml  # checks yaml files for parseable syntax.
      - id: destroyed-symlinks  # detects symlinks which are changed to regular files with a content of a path which that symlink was pointing to.
      - id: detect-private-key  # detects the presence of private keys.

  - repo: https://github.com/PyCQA/isort.git
    rev: '5.10.1'
    hooks:
      - id: isort

  -   repo: https://github.com/psf/black.git
      rev: '22.3.0'
      hooks:
      -   id: black
